### ISSUE TITLE
export pmml file has duplicate OutputField which casue loading pmml errors in spark.

### ISSUE THREAD

**Issue by rollingdeep** [jpmml/jpmml-sparkml-xgboost#13] opened 2019-08-09 10:09 UTC
## tail of xgb.pmml content
```
            <Segment id="2">
                <True/>
                <RegressionModel functionName="classification" normalizationMethod="logit" x-mathContext="float">
                    <MiningSchema>
                        <MiningField name="label" usageType="target"/>
                        <MiningField name="xgbValue"/>
                    </MiningSchema>
                    <Output>
                        <OutputField name="pmml(prediction)" optype="categorical" dataType="double" feature="predictedValue" isFinalResult="false"/>
                        <OutputField name="prediction" optype="categorical" dataType="double" feature="transformedValue">
                            <MapValues outputColumn="data:output" dataType="double">
<FieldColumnPair field="pmml(prediction)" column="data:input"/>
<InlineTable>
    <row> 
        <data:input>0</data:input>
        <data:output>0</data:output>
    </row>
    <row> 
        <data:input>1</data:input>
        <data:output>1</data:output>
    </row>
</InlineTable>
                            </MapValues>
                        </OutputField>
                        <OutputField name="probability(0)" optype="continuous" dataType="double" feature="probability" value="0"/>
                        <OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>
                        <OutputField name="probability(0)" optype="continuous" dataType="float" feature="probability" value="0"/>
                        <OutputField name="probability(1)" optype="continuous" dataType="float" feature="probability" value="1"/>
                    </Output>
                    <RegressionTable intercept="0.0" targetCategory="1">
                        <NumericPredictor name="xgbValue" coefficient="1.0"/>
                    </RegressionTable>
                    <RegressionTable intercept="0.0" targetCategory="0"/>
                </RegressionModel>
            </Segment>

```

## I found that the OutputField has duplicate values. if run, then throw errors.
```
rg.jpmml.evaluator.InvalidElementException: Element OutputField is not valid
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:61)
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:50)
	at org.jpmml.evaluator.ModelEvaluator$8.load(ModelEvaluator.java:1200)
	at org.jpmml.evaluator.ModelEvaluator$8.load(ModelEvaluator.java:1196)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at org.jpmml.evaluator.CacheUtil.getValue(CacheUtil.java:51)
	at org.jpmml.evaluator.ModelEvaluator.<init>(ModelEvaluator.java:183)
	at org.jpmml.evaluator.regression.RegressionModelEvaluator.<init>(RegressionModelEvaluator.java:64)
	at org.jpmml.evaluator.ModelEvaluatorFactory.createModelEvaluator(ModelEvaluatorFactory.java:118)
```

**Comment by vruusmann** [comment] 2019-08-09 10:32
This issue has got nothing to do with the JPMML-Evaluator project, so moving it here, as the offending PMML documents appears to contain Apache Spark and XGBoost related markup.

I'm expecting to see how this PMML document was generated. Otherwise, this issue will be closed as "not reproducible".

**Comment by rollingdeep** [comment] 2019-08-13 03:04
oh, thank you for your reply. The error can be reproduced.
It works very well on hdp2 + spark2.2.1 and pmml output label is correct. The above error appears when we update hdfs platform to hdp3.0 and update spark version from 2.2.1 to 2.3.2 and dependency jars.
this is code, xgboost 0.82 + spark2.3.2 + jpmml-sparkml-excuteable-1.4.9 + jpmml-xgboost-1.3.6 is being used now. The file wrote in scala with sbt compile tool.
``` 
    val estimator = new XGBoostClassifier(xgbParam).setFeaturesCol("features").setLabelCol("label")
    val pipeline = new Pipeline().setStages(Array[PipelineStage](assembler, estimator))
    val pipelineModel = pipeline.fit(trainData)

    val schema = trainData.schema
    val pmml = new PMMLBuilder(schema, pipelineModel).build()

    val conf = new Configuration()
    val modelDir = "/model/xgb.pmml"
    val path = new Path(modelDir)
    val fs = path.getFileSystem(conf)
    val out = fs.create(path, true)

    JAXBUtil.marshalPMML(pmml, new StreamResult(out)) //hdfs out
```

**Comment by vruusmann** [comment] 2019-08-13 04:37
@rollingdeep What is the data type of the `label` column? Integer, float, double, or something else? Could you share a toy dataset to make this example extra reproducible?

It should be impossible to generate a duplicate `OutputField` element (duplicate as having exactly the same name). However, in this case, this somehow happens, and I believe that one of the elements represents `probability(<integer 0>)` whereas the other is `probability(<double 0>)`.

**Comment by rollingdeep** [comment] 2019-08-13 09:03
Label column is double datatype.

I have checked your code. And found the error in project jpmml-sparkml-1.4.9 and in file ModelConverter.java about line 191 
```
List<OutputField> outputFields = output.getOutputFields();
outputFields.addAll(0, sparkOutputFields);
```
The first line outputFields have two result.
```
probability(0) | float
probability(1) | float
```
The second line outputFields have six result.
```
probability(0) | float
probability(1) | float
probability(0) | double
probability(1) | double
pmml(prediction) | double
prediction | double
```
I guess it must be xgboost train with float type. 
I changed your code, if outputFields are duplicate with sparkOutputFields, first merge outputFields  and discard the outputfield in sparkOutputFields. But, it cannot pass verify().

**Comment by vruusmann** [comment] 2019-08-23 04:39
> I guess the reason for this error is the inconsistency of data type between jpmml-xgboost and PMMLB Builder for output field.

@harumaj The method `org.jpmml.sparkml.ClassificationModelConverter#registerOutputFields(Label, SparkMLEncoder)` should set the data type attribute based on the "math context" of the enclosed model:
https://github.com/jpmml/jpmml-sparkml/blob/master/src/main/java/org/jpmml/sparkml/ClassificationModelConverter.java#L96

Apache Spark models report "math context" as `DataType.DOUBLE`, whereas XGBoost models report it as `DataType.FLOAT` instead.

The "math context" information is available via the `org.dmg.pmml.Model#getMathContext()` method.

**Comment by gowravshekar** [comment] 2020-03-21 11:52
Is the issue fixed in [jpmml-sparkml](https://github.com/jpmml/jpmml-sparkml)? The issue is reproducible in v1.5.7.

**Comment by vruusmann** [comment] 2020-03-21 13:12
This issue is still open, which means that the final technical fix has not been implemented and applied yet.

It can be fixed in the JPMML-SparkML-XGBoost library level. It's completely independent of the JPMML-SparkML library version.

The easiest fix would be to apply a visitor to the model object, which traverses its body and deletes all probability-type `OutputField` elements.

**Closed** 2020-03-24 21:40 UTC
