### ISSUE TITLE
LOAD PMML ERROR

### ISSUE THREAD

**Issue by Mantj** [jpmml/jpmml-sparkml-xgboost#15] opened 2020-04-01 08:58 UTC
hello, I'm using jpmml-xgboost-1.3.11, and I convert pipelineModel(contains XGBclassificationModel) to PMML succefully. But when I try to load to PMML using java, I got an ERROR.

I find that it is because the following part in PMML file:
![image](https://user-images.githubusercontent.com/18311407/78118459-9df10e00-7439-11ea-8e6d-8e5c2ae101be.png)
There are four lines of OutputField, the error occured because of the last two lines(where dataType=Float).
when I delete the last two lines, I can load the PMML success. 
And the same error occured when load PMML model with LGBclassificationModel, But it's OK when loading LR/GBDT/RF Model.
So how can I figure this error?Please help~

**Comment by vruusmann** [comment] 2020-04-01 14:35
Exact duplicate of https://github.com/jpmml/jpmml-sparkml-xgboost/issues/13

Please upgrade your application to latest library versions before reporting an issue.

**Closed as completed by vruusmann** 2020-04-01 14:35 UTC
